# Config for single device knowledge distillation (KD) in knowledge_distillation_single_device.py
# using a LLAMA3 teacher and student model
#
# This config assumes that you've ran the following commands before launching KD:
# First download the student and teacher models
#   tune download meta-llama/Llama-3.2-1B-Instruct --output-dir /tmp/Llama-3.2-1B-Instruct --ignore-patterns "original/consolidated.00.pth"
#   tune download meta-llama/Meta-Llama-3.2-3B-Instruct --output-dir /tmp/Meta-Llama-3.3-3B-Instruct --ignore-patterns "original/consolidated.00.pth"
#
# You get better results using KD if the teacher model has already been fine-tuned on the target dataset:
#   tune run lora_finetune_single_device --config llama3_2/3B_lora_single_device
#
# To launch on a single device, run the following command from root:
#   tune run knowledge_distillation_single_device --config llama3_2/knowledge_distillation_single_device
#
# This config works only for training on single device.


# Model Arguments
model:
  _component_: torchtune.models.llama3_2.lora_llama3_2_1b
  lora_attn_modules: ['q_proj', 'v_proj', 'output_proj']
  apply_lora_to_mlp: True
  apply_lora_to_output: False
  lora_rank: 64
  lora_alpha: 128
  lora_dropout: 0.0

teacher_model:
  _component_: torchtune.models.llama3_2.llama3_2_3b

output_hidden_states:
  student: [0, 1, 2]  # Choose layers from student model (16 layers total)
  teacher: [15, 20, 25] # Choose layers from teacher model (28 layers total)

layer_mapping:
  - [0, 0]  # Map first hidden state pair (student layer 0 → teacher layer 15)
  - [1, 1]  # Map second hidden state pair (student layer 1 → teacher layer 20)
  - [2, 2]  # Map third hidden state pair (student layer 2 → teacher layer 25)

loss_scaling:
  enabled: true # Enable or disable loss scaling
  method: "manual" # Scaling method: "manual" or "dynamic"
  manual_scales: # Scaling factors for manual method
    ce: 0.5
    kd: 0.2
    ir: 0.3


# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /content/drive/MyDrive/Distillation_project/base_models/Llama-3.2-1B-Instruct/original/tokenizer.model
  max_seq_len: null

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /content/drive/MyDrive/Distillation_project/base_models/Llama-3.2-1B-Instruct/
  checkpoint_files: [
    model.safetensors
  ]
  recipe_checkpoint: null
  output_dir: /content/drive/MyDrive/Distillation_project/distilled_models/3B-LoRA-1B-fkl-[[0,15],[1,20],[2,25]]
  model_type: LLAMA3
resume_from_checkpoint: False
save_adapter_weights_only: False

# Teacher checkpoint
teacher_checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /content/drive/MyDrive/Distillation_project/finetuned_models/Llama-3.2-3B-Instruct-LoRA-Finetuned/
  checkpoint_files: [
    hf_model_0001_0.pt,
    hf_model_0002_0.pt,
  ]
  recipe_checkpoint: null
  output_dir: /content/drive/MyDrive/Distillation_project/teacher_ckpts/Llama-3.2-3B-Instruct-LoRA-Finetuned-temp/
  model_type: LLAMA3

# Dataset and Sampler
dataset:
  _component_: torchtune.datasets.alpaca_cleaned_dataset
  packed: False  # True increases speed
seed: null
shuffle: True
batch_size: 4

# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW
  fused: True
  weight_decay: 0.01
  lr: 3e-4
lr_scheduler:
  _component_: torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss

kd_loss:
  _component_: torchtune.modules.loss.ForwardKLWithChunkedOutputLoss
kd_ratio: 0.5

# Training
epochs: 1
max_steps_per_epoch: 200
gradient_accumulation_steps: 8  # Use to increase virtual batch size
compile: False  # pytorch compile, set to true for better perf/memory

# Logging
# Logging
output_dir: "/content/drive/MyDrive/Distillation_project/Logs"
metric_logger:
  _component_: torchtune.training.metric_logging.WandBLogger
  project: "llama3.2_distillation" # Name of the W&B project
log_every_n_steps: 1
log_peak_memory_stats: True

# Environment
device: cuda
dtype: bf16

# Activations Memory
enable_activation_checkpointing: False  # True reduces memory

# Profiler (disabled)
profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: False

  #Output directory of trace artifacts
  output_dir: ${output_dir}/profiling_outputs

  #`torch.profiler.ProfilerActivity` types to trace
  cpu: True
  cuda: True

  #trace options passed to `torch.profiler.profile`
  profile_memory: False
  with_stack: False
  record_shapes: True
  with_flops: False

  # `torch.profiler.schedule` options:
  # wait_steps -> wait, warmup_steps -> warmup, active_steps -> active, num_cycles -> repeat
  wait_steps: 5
  warmup_steps: 3
  active_steps: 2
  num_cycles: 1
